- name: Demo on Play Level Variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}

# In Ansible variable will be accessed using {{ }}
# Ansible supports double quotes and single quotes also, However quotes are not mandatory
# Quotes are mandatory if value starts with a variable meaning:
# msg: {{ URL }} <- This requires quoting
#msg: URL - {{ URL }} <- This does not require quoting

- name: Demo on Task Level Variables
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}
      vars:
        URL: play.example.com

# Only this task will have the variable, and other task can't access it

- name: Load Variables from file
  hosts: all
  vars_files:
    - exvars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}

# vars_files does not support task level, it is only for play level

- name: Variable from Roles
  hosts: all
  vars:
    URL_PLAY: play.example.com
  roles:
    - sample

# Variable from Roles

- name: Demo on register variables
  hosts: all
  tasks:
    - name: Run uptime shell command
      ansible.builtin.shell: uptime
      register: output
    - name: Print Output
      ansible.builtin.debug:
        msg: '{{ output }}'