- name: Demo on loops
  hosts: localhost
  connection: local
  tasks:
    - name: Demo task for loops
      ansible.builtin.debug:
        msg: Fruit Name - {{item}}
      loop:
        - apple
        - banana

    - name: Demo task for loops
      ansible.builtin.debug:
        msg: Fruit Name - {{item.name}}, Quantity - {{item.quantity}}
      loop:
        - {name: apple, quantity: 10}
        - {name: banana, quantity: 20}